# Generated by Django 2.1.7 on 2019-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_updated_at'),
        ('blog', '0003_auto_20190326_1253'),
    ]

    operations = [
    ]
