# Generated by Django 2.1.7 on 2019-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_tags'),
        ('shop', '0005_auto_20190421_1701'),
    ]

    operations = [
    ]
